### PR TITLE
Merge realtime laser PWM code into current grbl upstream v0.9i

### PR DESCRIPTION
**Pull request by michaelfranzl**
The master branch of GRBL upstream was updated to v0.9i on March 16, 2015. I've merged your realtime laser PWM code changes with the newest official GRBL. There were only 5 merge conflicts: 4 were header changes, and 1 had to do with report.c. All of them were very trivial to resolve. By the way, thank you for your efforts for getting realtime PWM working!

### CODE REVIEW

**Comment by villamany** [comment]
Hi, im getting much better speed peformance with the 0.9h than 0.9i. 0.9i has many "micropauses". I notice it mainly on grayscale image engravings. 
With 0.9h i can get 3000mm/min without these issues, on 0.9i they are noticed also at 1000mm/min.

Same setting on both.

**Comment by alpharesearch** [comment]
If you want to send me a pull request I will commit the changes...

**Comment by villamany** [comment]
No any changes, only use the previous version to last merge

**Comment by alpharesearch** [comment]
From my simulator test it looks like the new i version is much faster... but if you having it running on the real hardware I guess it would be better to wait if you have issues or try to find what changed. I think @chamnit is adding some kind of laser support at one point. But I'm not sure when this will be...
image

**Comment by chamnit** [comment]
@alpharesearch : Soon-ish. I've been quite busy with other pressing matters.

**Comment by villamany** [comment]
Yes, on grayscale image engravings the buffer reported by grbl is maintained most of time at 17 with 0.9h and at 0-2 with 0.9i producing these micro pauses and un-smooth engravings.... thanks for the work guys!

**Pull request merged**
